// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdtz_cUWRW2FzZ_lc8H8rEWJZ0JEHElTU',
    appId: '1:289460201050:web:d2b3ace3e87f26c1a81a63',
    messagingSenderId: '289460201050',
    projectId: 'quizapp-a3acd',
    authDomain: 'quizapp-a3acd.firebaseapp.com',
    storageBucket: 'quizapp-a3acd.appspot.com',
    measurementId: 'G-QLPMZ9PG61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiYlaDBCxPDUvYieWFPDWJgaqwzPd-gmM',
    appId: '1:289460201050:android:325b157e0570b762a81a63',
    messagingSenderId: '289460201050',
    projectId: 'quizapp-a3acd',
    storageBucket: 'quizapp-a3acd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeZv2tQxax2xyRxDmuOoQZ15pgRLGdQxg',
    appId: '1:289460201050:ios:5d60e87c6b02df55a81a63',
    messagingSenderId: '289460201050',
    projectId: 'quizapp-a3acd',
    storageBucket: 'quizapp-a3acd.appspot.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeZv2tQxax2xyRxDmuOoQZ15pgRLGdQxg',
    appId: '1:289460201050:ios:7c6cc8d6e246a599a81a63',
    messagingSenderId: '289460201050',
    projectId: 'quizapp-a3acd',
    storageBucket: 'quizapp-a3acd.appspot.com',
    iosBundleId: 'com.example.quizapp.RunnerTests',
  );
}
